lab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from lab import views

app_name = 'lab'

urlpatterns = [
    path('', views.home_page, name='homePage'),
    path(r'admindash/', views.admin_dashboard, name='adminDash'),
    path(r'joinsession/', views.player_join, name='playerJoin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pearlinlab/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('lab.urls', 'lab'), namespace='lab')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/models.py
from django.db import models

# Create your models here.

lab/views.py
from django.shortcuts import render


def home_page(request):
    context = {
        'title': 'Home Page'
    }
    return render(request, 'lab/home_page.html', context)


def admin_dashboard(request):
    context = {
        'title': 'Admin Dashboard'
    }
    return render(request, 'lab/landing_page.html', context)


def player_join(request):
    context = {
        'title': 'Join Session'
    }
    return render(request, 'lab/landing_page.html', context)

admin_control/templates/admin_control/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PearlInLab</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

admin_control/templates/admin_control/home_page.html
{% extends 'admin_control/base.html' %}
{% load static %}
{% block body %}

    <iframe src="{% static 'webgl/index.html' %}"
            width="100%"
            height="680px"
            title="VRMap">

        Browser not compatible.

    </iframe>
{% endblock %}

lab/templates/lab/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>
    {% block header %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

lab/templates/lab/home_page.html
{% extends 'lab/base.html' %}
{% load static %}
{% block header %}
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }

        .background-div {
            background-image: url("{% static 'images/pexels-jeffrey-czum-3330118.jpg' %}");
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        p {
            color: white;
            margin: 0;
            position: relative;
            top: -12.5%;
            left: 112.5%;
            transform: translate(-50%, -50%);
        }

        img:hover {
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
    </style>
{% endblock %}
{% block body %}
    <div class="background-div">
        <div class="jumbotron d-flex align-items-end min-vh-100 m-0" style="background-color: transparent">
            <div class="container">
                <div class="row">
                    <h1 class="text-light mx-auto">Welcome to Pearlin Lab</h1>
                </div>
                <div class="row">
                    <div class="col-lg-2 ml-0">
                        <a href="{% url 'lab:adminDash' %}">
                            <img src="{% static 'images/wood_texture.jpg' %}" class="h-25">
                            <p>Admin</p>
                        </a>
                    </div>
                    <div class="col-lg-2 ml-auto">
                        <a href="{% url 'lab:playerJoin' %}">
                            <img src="{% static 'images/wood_texture.jpg' %}" class="h-25">
                            <p>Players</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

lab/templates/lab/landing_page.html
{% extends 'lab/base.html' %}
{% load static %}
{% block body %}

    <iframe src="{% static 'webgl/index.html' %}"
            width="100%"
            height="680px"
            title="VRMap">

        Browser not compatible.

    </iframe>
{% endblock %}